language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  # giacocorsiglia/stubs-generator does not support PHP 7.0
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4snapshot"

before_install:
  - phpenv config-rm xdebug.ini
  - composer validate --strict

install:
  - composer install --no-interaction --no-suggest

before_script:
  - mkdir -p .build/php-cs-fixer
  - cat ./wordpress/wp-includes/version.php
  - php -m

script:
  - bash -x ./generate.sh
  - php -l ./wordpress-stubs.php
  - git diff --exit-code
